### ISSUE TITLE
meta-karo

### ISSUE THREAD

**Issue by luzik** [karo-electronics/welcome#1]
Please consider making use of native Yocto layers system and transform forked fsl-arm-extra/meta-freescale-3rdparty into your own meta-karo layer or just sync your work into meta-freescale-3rdparty rocko branch

**Comment by luzik** [comment]
any one reading this ?

**Comment by oliverwendt** [comment]
Yes. Didn't get a notification about the first message, sorry about that. 
... **But:** This is not appropriate place to write this, topic is "meta-fsl-arm-extra", so it should be written in "meta-fsl-arm-extra".

To your question:
We are working on that, yet I can't comment on WIP projects.

**Comment by luzik** [comment]
Yeah, I know ..but issuses in "meta-fsl-arm-extra" are disabled.
I have some patches to get current karo u-boot working with rocko. If you are interested I can do PR on that. But if you  working on it, than you probably have that already figured out, or moved to more recent u-boot.
Looking forward to get that new layer or meta-freescale-3rdparty update

**Comment by luzik** [comment]
meta-karo added
Thank You
